image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  GIT_DEPTH: 1

stages:
  - build
#  - publish

build:
  stage: build
  script:
    - './build.cmd GitHubRelease -configuration Release'
  artifacts:
    paths:
      - publish/

#publish:
#  stage: publish
#  only:
#    - tags
#  script:
#    - './build.cmd PublishNuGetPackage -configuration Release'